// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8oj9JrINkj2bJ8yaDX3KFLrt4I0ecmLo',
    appId: '1:182995615087:web:90aabbfa52db55dfd8fc9a',
    messagingSenderId: '182995615087',
    projectId: 'learningprocess-826b3',
    authDomain: 'learningprocess-826b3.firebaseapp.com',
    storageBucket: 'learningprocess-826b3.appspot.com',
    measurementId: 'G-JDP5X77NN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwNy42iAY5Sm39hLjS7ueEwc93SaNxlho',
    appId: '1:182995615087:android:7cd2d02dc6dd60bad8fc9a',
    messagingSenderId: '182995615087',
    projectId: 'learningprocess-826b3',
    storageBucket: 'learningprocess-826b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjbeIg1GIMrwtIUifCuLq_hFWMmsbtgQ',
    appId: '1:182995615087:ios:197a72962aa36e9ed8fc9a',
    messagingSenderId: '182995615087',
    projectId: 'learningprocess-826b3',
    storageBucket: 'learningprocess-826b3.appspot.com',
    iosClientId: '182995615087-5511ncupgeg8lqnc5shm1nvl06q4pbhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiIntegrator',
  );
}
